# Generated by Django 4.2.2 on 2023-11-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="soyad",
            field=models.CharField(max_length=100),
        ),
    ]
